
###
GET  http://localhost:3000/admins
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzRiZDUyMzRjMjk5MTc0MzQyZDdhMyIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDY5NzQwNSwiZXhwIjoxNjkwNzgzODA1fQ.mmbemJBfK07UKPKkaSDjcV730lmfB33BBOHqIC3Ms7o

###
GET  http://localhost:3000/admins/64c3ad46b00cc6fc40b10fd2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzNhNzlkNmY4NmUxYzU3ZTBkMzgyYSIsImlzX3N1cGVyIjp0cnVlfSwiaWF0IjoxNjkwNjEwOTM5LCJleHAiOjE2OTA2OTczMzl9.yApqyDvAfZ3Mj3_pc_BPQi9KarMV7BM65AB_T3iKkEg


###
POST  http://localhost:3000/admins/login
Content-Type: application/json

{
  "username": "leo",
  "password": "1234"
}


###
POST http://localhost:3000/admins
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzNhNzlkNmY4NmUxYzU3ZTBkMzgyYSIsImlzX3N1cGVyIjp0cnVlfSwiaWF0IjoxNjkwNjEwOTM5LCJleHAiOjE2OTA2OTczMzl9.yApqyDvAfZ3Mj3_pc_BPQi9KarMV7BM65AB_T3iKkEg
Content-Type: application/json

{
  "full_name": "Leo Messi",
  "username": "teo",
  "password": "1234"
}

###
PATCH   http://localhost:3000/admins/64c4bd5234c299174342d7a3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzRiZDUyMzRjMjk5MTc0MzQyZDdhMyIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDY5NzQwNSwiZXhwIjoxNjkwNzgzODA1fQ.mmbemJBfK07UKPKkaSDjcV730lmfB33BBOHqIC3Ms7o
Content-Type: application/json

{
  "full_name": "Akasi",
  "username": "tel"
}

###
PATCH   http://localhost:3000/admins/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzRiZDUyMzRjMjk5MTc0MzQyZDdhMyIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDY5NzQwNSwiZXhwIjoxNjkwNzgzODA1fQ.mmbemJBfK07UKPKkaSDjcV730lmfB33BBOHqIC3Ms7o
Content-Type: application/json

{
  "full_name": "jone",
  "username": "jone"
}

###
DELETE   http://localhost:3000/admins/64b8144f0f9d5d16444416a1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzRiZDUyMzRjMjk5MTc0MzQyZDdhMyIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDY5NzQwNSwiZXhwIjoxNjkwNzgzODA1fQ.mmbemJBfK07UKPKkaSDjcV730lmfB33BBOHqIC3Ms7o
