
###
GET  http://localhost:3000/borrowers
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzhkZTE5OTUwNDU3ZjVhZDZmMDdlNiIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDg4NTkxMywiZXhwIjoxNjkwOTcyMzEzfQ.VGtbk22tUs9QbLCdZgf7VgnQQwWtUruQNNcOpAM2uxg



###
GET  http://localhost:3000/borrowers/64c60413ed5850fea377f0ad
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzhkZTE5OTUwNDU3ZjVhZDZmMDdlNiIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDg4NTkxMywiZXhwIjoxNjkwOTcyMzEzfQ.VGtbk22tUs9QbLCdZgf7VgnQQwWtUruQNNcOpAM2uxg



###
POST http://localhost:3000/borrowers
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzhkZTE5OTUwNDU3ZjVhZDZmMDdlNiIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDg4NTkxMywiZXhwIjoxNjkwOTcyMzEzfQ.VGtbk22tUs9QbLCdZgf7VgnQQwWtUruQNNcOpAM2uxg
Content-Type: application/json

{
  "full_name": "Jone doe",
  "address": "Chilonzor",
  "phone": "+998900010101"
}

###
PATCH   http://localhost:3000/borrowers/64c60413ed5850fea377f0ad
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzhkZTE5OTUwNDU3ZjVhZDZmMDdlNiIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDg4NTkxMywiZXhwIjoxNjkwOTcyMzEzfQ.VGtbk22tUs9QbLCdZgf7VgnQQwWtUruQNNcOpAM2uxg

Content-Type: application/json

{
  "full_name": "Jone Doe",
  "address": "Chilonzor",
  "phone": "+998900010102"
}

###
DELETE   http://localhost:3000/borrowers/64c60413ed5850fea377f0ad
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6eyJpZCI6IjY0YzhkZTE5OTUwNDU3ZjVhZDZmMDdlNiIsImlzX3N1cGVyIjpmYWxzZX0sImlhdCI6MTY5MDg4NTkxMywiZXhwIjoxNjkwOTcyMzEzfQ.VGtbk22tUs9QbLCdZgf7VgnQQwWtUruQNNcOpAM2uxg
